---
apiVersion: v1
kind: Pod
metadata:
  name: productcatalog
  labels:
    name: productcatalog
    tier: app
spec:
  containers:
  - name: productcatalog
    imagePullPolicy: Always
    image: phani997/productcatalogservice:v1
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
spec:
  selector:
    name:  productcatalog
    tier: app
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550